(function () {
	angular
		.module('myApp.mockData', [])
		.value('mockData', {'data': [{
    'id': 1,
    'first_name': 'John',
    'last_name': 'Ray',
    'email': 'jray0@discuz.net',
    'country': 'Indonesia',
    'ip_address': '173.94.46.203'
  }, {
    'id': 2,
    'first_name': 'Nicole',
    'last_name': 'James',
    'email': 'njames1@comsenz.com',
    'country': 'Venezuela',
    'ip_address': '118.81.62.225'
  }, {
    'id': 3,
    'first_name': 'Kevin',
    'last_name': 'Johnson',
    'email': 'kjohnson2@pbs.org',
    'country': 'Ukraine',
    'ip_address': '193.202.248.31'
  }, {
    'id': 4,
    'first_name': 'Philip',
    'last_name': 'Washington',
    'email': 'pwashington3@psu.edu',
    'country': 'Tunisia',
    'ip_address': '199.107.198.111'
  }, {
    'id': 5,
    'first_name': 'Roger',
    'last_name': 'Ross',
    'email': 'rross4@multiply.com',
    'country': 'Colombia',
    'ip_address': '118.40.65.241'
  }, {
    'id': 6,
    'first_name': 'Kevin',
    'last_name': 'Sullivan',
    'email': 'ksullivan5@wikipedia.org',
    'country': 'South Korea',
    'ip_address': '51.194.108.24'
  }, {
    'id': 7,
    'first_name': 'Martha',
    'last_name': 'Mcdonald',
    'email': 'mmcdonald6@furl.net',
    'country': 'China',
    'ip_address': '198.204.192.83'
  }, {
    'id': 8,
    'first_name': 'Lillian',
    'last_name': 'Stevens',
    'email': 'lstevens7@bloglines.com',
    'country': 'Iceland',
    'ip_address': '33.118.243.246'
  }, {
    'id': 9,
    'first_name': 'Henry',
    'last_name': 'Rice',
    'email': 'hrice8@theglobeandmail.com',
    'country': 'Iran',
    'ip_address': '180.169.118.83'
  }, {
    'id': 10,
    'first_name': 'Eugene',
    'last_name': 'Johnson',
    'email': 'ejohnson9@theguardian.com',
    'country': 'Philippines',
    'ip_address': '247.50.195.162'
  }, {
    'id': 11,
    'first_name': 'Victor',
    'last_name': 'Gordon',
    'email': 'vgordona@ning.com',
    'country': 'Thailand',
    'ip_address': '21.180.23.98'
  }, {
    'id': 12,
    'first_name': 'Ruby',
    'last_name': 'Harris',
    'email': 'rharrisb@opensource.org',
    'country': 'Japan',
    'ip_address': '70.237.128.108'
  }, {
    'id': 13,
    'first_name': 'Joe',
    'last_name': 'Hunt',
    'email': 'jhuntc@ifeng.com',
    'country': 'China',
    'ip_address': '129.184.187.182'
  }, {
    'id': 14,
    'first_name': 'Jeremy',
    'last_name': 'Coleman',
    'email': 'jcolemand@psu.edu',
    'country': 'France',
    'ip_address': '190.165.149.244'
  }, {
    'id': 15,
    'first_name': 'James',
    'last_name': 'Thomas',
    'email': 'jthomase@twitter.com',
    'country': 'Afghanistan',
    'ip_address': '102.157.110.142'
  }, {
    'id': 16,
    'first_name': 'Diane',
    'last_name': 'Ross',
    'email': 'drossf@dion.ne.jp',
    'country': 'Portugal',
    'ip_address': '44.8.129.44'
  }, {
    'id': 17,
    'first_name': 'Paula',
    'last_name': 'Lane',
    'email': 'planeg@sourceforge.net',
    'country': 'Brazil',
    'ip_address': '116.110.104.126'
  }, {
    'id': 18,
    'first_name': 'Paul',
    'last_name': 'Kelly',
    'email': 'pkellyh@nbcnews.com',
    'country': 'Sweden',
    'ip_address': '51.92.98.183'
  }, {
    'id': 19,
    'first_name': 'Gerald',
    'last_name': 'Wallace',
    'email': 'gwallacei@tiny.cc',
    'country': 'Cuba',
    'ip_address': '12.80.140.208'
  }, {
    'id': 20,
    'first_name': 'Marie',
    'last_name': 'Hughes',
    'email': 'mhughesj@plala.or.jp',
    'country': 'Poland',
    'ip_address': '132.230.99.227'
  }, {
    'id': 21,
    'first_name': 'Bonnie',
    'last_name': 'Powell',
    'email': 'bpowellk@washingtonpost.com',
    'country': 'Sweden',
    'ip_address': '179.193.46.232'
  }, {
    'id': 22,
    'first_name': 'Jonathan',
    'last_name': 'Fields',
    'email': 'jfieldsl@pen.io',
    'country': 'France',
    'ip_address': '113.97.214.6'
  }, {
    'id': 23,
    'first_name': 'Irene',
    'last_name': 'Welch',
    'email': 'iwelchm@livejournal.com',
    'country': 'China',
    'ip_address': '198.200.44.54'
  }, {
    'id': 24,
    'first_name': 'Lori',
    'last_name': 'Marshall',
    'email': 'lmarshalln@discovery.com',
    'country': 'Indonesia',
    'ip_address': '15.94.212.175'
  }, {
    'id': 25,
    'first_name': 'Katherine',
    'last_name': 'Lewis',
    'email': 'klewiso@ezinearticles.com',
    'country': 'Indonesia',
    'ip_address': '41.220.217.115'
  }, {
    'id': 26,
    'first_name': 'Jerry',
    'last_name': 'Bryant',
    'email': 'jbryantp@yahoo.co.jp',
    'country': 'China',
    'ip_address': '233.187.54.93'
  }, {
    'id': 27,
    'first_name': 'Ann',
    'last_name': 'Russell',
    'email': 'arussellq@webnode.com',
    'country': 'Philippines',
    'ip_address': '99.42.47.43'
  }, {
    'id': 28,
    'first_name': 'Michelle',
    'last_name': 'Kelly',
    'email': 'mkellyr@bigcartel.com',
    'country': 'Portugal',
    'ip_address': '14.124.219.76'
  }, {
    'id': 29,
    'first_name': 'Laura',
    'last_name': 'Olson',
    'email': 'lolsons@timesonline.co.uk',
    'country': 'Chile',
    'ip_address': '233.48.36.242'
  }, {
    'id': 30,
    'first_name': 'Louis',
    'last_name': 'Lopez',
    'email': 'llopezt@drupal.org',
    'country': 'Brazil',
    'ip_address': '69.131.219.176'
  }, {
    'id': 31,
    'first_name': 'Timothy',
    'last_name': 'Arnold',
    'email': 'tarnoldu@illinois.edu',
    'country': 'China',
    'ip_address': '178.31.1.213'
  }, {
    'id': 32,
    'first_name': 'Jerry',
    'last_name': 'Gordon',
    'email': 'jgordonv@diigo.com',
    'country': 'China',
    'ip_address': '135.29.169.166'
  }, {
    'id': 33,
    'first_name': 'Tina',
    'last_name': 'Mcdonald',
    'email': 'tmcdonaldw@arstechnica.com',
    'country': 'China',
    'ip_address': '132.85.234.25'
  }, {
    'id': 34,
    'first_name': 'Jean',
    'last_name': 'Harper',
    'email': 'jharperx@unicef.org',
    'country': 'Japan',
    'ip_address': '230.32.39.79'
  }, {
    'id': 35,
    'first_name': 'Margaret',
    'last_name': 'Diaz',
    'email': 'mdiazy@rakuten.co.jp',
    'country': 'Ethiopia',
    'ip_address': '2.117.14.244'
  }, {
    'id': 36,
    'first_name': 'Donna',
    'last_name': 'Perez',
    'email': 'dperezz@shutterfly.com',
    'country': 'Indonesia',
    'ip_address': '186.24.236.61'
  }, {
    'id': 37,
    'first_name': 'William',
    'last_name': 'Palmer',
    'email': 'wpalmer10@tripadvisor.com',
    'country': 'Norway',
    'ip_address': '168.152.226.79'
  }, {
    'id': 38,
    'first_name': 'Pamela',
    'last_name': 'Holmes',
    'email': 'pholmes11@bloomberg.com',
    'country': 'Costa Rica',
    'ip_address': '48.145.219.59'
  }, {
    'id': 39,
    'first_name': 'Jerry',
    'last_name': 'Franklin',
    'email': 'jfranklin12@nytimes.com',
    'country': 'China',
    'ip_address': '169.18.149.181'
  }, {
    'id': 40,
    'first_name': 'Kelly',
    'last_name': 'Meyer',
    'email': 'kmeyer13@patch.com',
    'country': 'Poland',
    'ip_address': '112.14.206.43'
  }, {
    'id': 41,
    'first_name': 'Jerry',
    'last_name': 'Andrews',
    'email': 'jandrews14@prlog.org',
    'country': 'Cuba',
    'ip_address': '32.221.110.155'
  }, {
    'id': 42,
    'first_name': 'Evelyn',
    'last_name': 'Coleman',
    'email': 'ecoleman15@umich.edu',
    'country': 'Czech Republic',
    'ip_address': '159.209.201.242'
  }, {
    'id': 43,
    'first_name': 'Susan',
    'last_name': 'Flores',
    'email': 'sflores16@pbs.org',
    'country': 'Indonesia',
    'ip_address': '204.21.74.130'
  }, {
    'id': 44,
    'first_name': 'Barbara',
    'last_name': 'Phillips',
    'email': 'bphillips17@cdc.gov',
    'country': 'China',
    'ip_address': '16.180.242.91'
  }, {
    'id': 45,
    'first_name': 'Carl',
    'last_name': 'Howard',
    'email': 'choward18@npr.org',
    'country': 'Russia',
    'ip_address': '112.64.26.27'
  }, {
    'id': 46,
    'first_name': 'Paul',
    'last_name': 'Hernandez',
    'email': 'phernandez19@si.edu',
    'country': 'Canada',
    'ip_address': '48.15.207.113'
  }, {
    'id': 47,
    'first_name': 'Mary',
    'last_name': 'Olson',
    'email': 'molson1a@google.com',
    'country': 'Yemen',
    'ip_address': '183.144.17.165'
  }, {
    'id': 48,
    'first_name': 'Wanda',
    'last_name': 'Robinson',
    'email': 'wrobinson1b@ebay.com',
    'country': 'Colombia',
    'ip_address': '42.237.67.158'
  }, {
    'id': 49,
    'first_name': 'Amy',
    'last_name': 'Harris',
    'email': 'aharris1c@economist.com',
    'country': 'Indonesia',
    'ip_address': '79.180.147.117'
  }, {
    'id': 50,
    'first_name': 'Juan',
    'last_name': 'Meyer',
    'email': 'jmeyer1d@tiny.cc',
    'country': 'Greece',
    'ip_address': '63.22.42.241'
  }]});
}());