/*
Do NOT manually edit this file, these tests were generated by "npm run testExamples".
Changes to this file may cause incorrect behavior and will be lost when tests are rerun.
*/
// JavaScript
describe('My App', function () {
  // JavaScript
  describe('default route', function () {
    it('should automatically redirect to / when location hash/fragment is empty', function () {
      browser().navigateTo('index.html');
      expect(browser().location().url()).toBe('/');
    });
  
    it('should automatically redirect to / when location hash/fragment is invalid', function () {
      browser().navigateTo('#/foo-bar-bas');
      expect(browser().location().url()).toBe('/');
    });
  
    it('should not automatically redirect to / when location hash/fragment is valid', function () {
      browser().navigateTo('#/about');
      expect(browser().location().url()).toBe('/about');
    });
  });
  
// JavaScript
  describe('my view', function () {
    beforeEach(function () {
      browser().navigateTo('#/');
    });
  
    it('should contain expected text', function () {
      expect(element('[ng-view] p:first').text())
        .toBe('this is the home page.');
    });
  });
  
// JavaScript
  describe('my view', function () {
    beforeEach(function () {
      browser().navigateTo('#/');
    });
  
    it('should contain my directive tag', function () {
      var elm = element('[ng-view] my-dir');
      expect(elm.count()).toBe(1);
    });
  });
  
// JavaScript
  describe('my view', function () {
    beforeEach(function () {
      browser().navigateTo('#/');
    });
  
    it('should contain my directive attribute', function () {
      var elm = element('[ng-view] [my-dir]');
      expect(elm.count()).toBe(1);
    });
  });
  
// JavaScript
  describe('my view', function () {
    beforeEach(function () {
      browser().navigateTo('#/');
    });
  
    it('should contain my directive class name', function () {
      var elm = element('[ng-view] .my-dir');
      expect(elm.count()).toBe(1);
    });
  });
  
});
